require 'httparty'
require 'active_support'

module Smite
end

require 'smite/object.rb'
require 'smite/queue.rb'
require 'smite/motd.rb'
require 'smite/recommended_items.rb'
require 'smite/achievements.rb'
require 'smite/ability.rb'
require 'smite/god_rank.rb'
require 'smite/god_stats.rb'
require 'smite/god.rb'
require 'smite/item_effect.rb'
require 'smite/item.rb'
require 'smite/friend.rb'
require 'smite/data_transform.rb'
require 'smite/match_achievements.rb'
require 'smite/competitor.rb'
require 'smite/full_match.rb'
require 'smite/match_summary.rb'
require 'smite/player.rb'
require 'smite/game.rb'
require 'smite/client.rb'